import { normalizeItem, type InventoryItem } from "@/types/inventory"

const raw: Omit<InventoryItem, "status">[] = [
  {
    id: "inv-001",
    name: "Ventilator — ICU Pro",
    category: "ICU",
    ward: "Ward C",
    sku: "EQ-ICU-VNT-01",
    total: 24,
    available: 6,
    inUse: 14,
    reserved: 4,
    lowStockThreshold: 5,
    lastAudit: "2026-03-27",
    dailyUseAvg: 3.2,
  },
  {
    id: "inv-002",
    name: "Patient Monitor — Multi-parameter",
    category: "ICU",
    ward: "Ward C",
    sku: "EQ-ICU-MON-02",
    total: 48,
    available: 22,
    inUse: 20,
    reserved: 6,
    lowStockThreshold: 8,
    lastAudit: "2026-03-28",
    dailyUseAvg: 5.1,
  },
  {
    id: "inv-003",
    name: "Infusion Pump",
    category: "General",
    ward: "Ward A",
    sku: "EQ-GEN-INF-03",
    total: 120,
    available: 45,
    inUse: 62,
    reserved: 13,
    lowStockThreshold: 15,
    lastAudit: "2026-03-28",
    dailyUseAvg: 12,
  },
  {
    id: "inv-004",
    name: "Portable Ultrasound",
    category: "Emergency",
    ward: "Ward B",
    sku: "EQ-ER-US-04",
    total: 8,
    available: 2,
    inUse: 4,
    reserved: 2,
    lowStockThreshold: 2,
    lastAudit: "2026-03-26",
    dailyUseAvg: 1.1,
  },
  {
    id: "inv-005",
    name: "Defibrillator / AED",
    category: "Emergency",
    ward: "Ward B",
    sku: "EQ-ER-AED-05",
    total: 16,
    available: 9,
    inUse: 5,
    reserved: 2,
    lowStockThreshold: 3,
    lastAudit: "2026-03-28",
    dailyUseAvg: 2.4,
  },
  {
    id: "inv-006",
    name: "Surgical Instrument Set — Ortho",
    category: "General",
    ward: "OR Suite",
    sku: "EQ-OR-ORT-06",
    total: 32,
    available: 14,
    inUse: 12,
    reserved: 6,
    lowStockThreshold: 6,
    lastAudit: "2026-03-25",
    dailyUseAvg: 4,
  },
  {
    id: "inv-007",
    name: "Wheelchair — Transport",
    category: "General",
    ward: "Central Store",
    sku: "EQ-GEN-WC-07",
    total: 55,
    available: 28,
    inUse: 18,
    reserved: 9,
    lowStockThreshold: 10,
    lastAudit: "2026-03-28",
    dailyUseAvg: 8,
  },
  {
    id: "inv-008",
    name: "ECMO Circuit Kit",
    category: "ICU",
    ward: "Ward C",
    sku: "EQ-ICU-ECM-08",
    total: 6,
    available: 1,
    inUse: 4,
    reserved: 1,
    lowStockThreshold: 2,
    lastAudit: "2026-03-27",
    dailyUseAvg: 0.4,
  },
  {
    id: "inv-009",
    name: "Crash Cart — Standard",
    category: "Emergency",
    ward: "Ward B",
    sku: "EQ-ER-CRT-09",
    total: 10,
    available: 4,
    inUse: 4,
    reserved: 2,
    lowStockThreshold: 2,
    lastAudit: "2026-03-28",
    dailyUseAvg: 1.8,
  },
  {
    id: "inv-010",
    name: "Nebulizer",
    category: "General",
    ward: "Ward A",
    sku: "EQ-GEN-NEB-10",
    total: 40,
    available: 18,
    inUse: 17,
    reserved: 5,
    lowStockThreshold: 8,
    lastAudit: "2026-03-28",
    dailyUseAvg: 6,
  },
  {
    id: "inv-011",
    name: "Blood Pressure Cuff Set",
    category: "General",
    ward: "Central Store",
    sku: "EQ-GEN-BP-11",
    total: 200,
    available: 95,
    inUse: 85,
    reserved: 20,
    lowStockThreshold: 25,
    lastAudit: "2026-03-28",
    dailyUseAvg: 22,
  },
  {
    id: "inv-012",
    name: "Suction Unit — Wall",
    category: "ICU",
    ward: "Ward C",
    sku: "EQ-ICU-SUC-12",
    total: 36,
    available: 8,
    inUse: 22,
    reserved: 6,
    lowStockThreshold: 8,
    lastAudit: "2026-03-27",
    dailyUseAvg: 3.5,
  },
]

export const INVENTORY_SEED: InventoryItem[] = raw.map(normalizeItem)
